<?php
/**
 * Module routing
 */
function planetVO_menu()
{
    $items['planetVO'] = array(
        'title' => t('Import planetVO data in your site'),
        'page callback' => 'planetvo_content',
        'access arguments' => array(true),
        'type' => MENU_CALLBACK,
      );

      $items['admin/config/system/planetvo'] = array(
        'title' => t('planetVO settings'),
        'description' => t('planetVO configuration page'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('planetvo_admin_settings'),
        'access arguments' => array('Importer configuration'),
        'type' => MENU_NORMAL_ITEM,
      );
      
      
      $items['admin/config/system/planetvo/cron'] = array(
        'title' => t('planetVO settings'),
        'description' => t('planetVO CRON running'),
        'page callback' => 'cron_task_import',
        'page arguments' => array(),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
      );

      return $items; 
}

/**
 * Configuration form
 */
function planetvo_admin_settings()
{
  $form['planetvo_server'] = array(
    '#type' => 'textfield',
    '#title' => t('FTP server'),
    '#description' => t('FTP Server access'),
    '#default_value' => variable_get('planetvo_server'),
  );
  
  $form['planetvo_login'] = array(
    '#type' => 'textfield',
    '#title' => t('Login'),
    '#description' => t('FTP Server login'),
    '#default_value' => variable_get('planetvo_login'),
  );
  
  $form['planetvo_pwd'] = array(
    '#type' => 'textfield',
    '#title' => t('Password'),
    '#description' => t('FTP Server password'),
    '#default_value' => variable_get('planetvo_pwd'),
  );
  
  $form['planetvo_code'] = array(
    '#type' => 'textfield',
    '#title' => t('planetVO code'),
    '#description' => t('Séparés par des virgules. Ex: tt4, rr5, vv6'),
    '#default_value' => variable_get('planetvo_code'),
  );
  
  return system_settings_form($form);
}

/**
 * CRON task
 */
function planetvo_cron()
{
    
    //cron_task_import();       
    //watchdog('cron_planetvo', 'cron_planetvo ran');
    die('là');
    
    
}

/**
 * the import task
 */
function cron_task_import()
{
    watchdog('cron_planetvo', 'cron_planetvo begin running');
    $limit_time = set_time_limit(0);
    
    ini_set('max_execution_time', 0);
    ini_set('memory_limit', -1);
    
    //if(!$limit_time) die('Impossible d\'augmenter le temps d\'execution.');
    
    //unpublish every cars saved
    $query = db_query("UPDATE {node} AS n LEFT JOIN field_data_field_code_pvo AS f ON f.entity_id = n.nid SET n.`status` = '0' WHERE n.`type` =:type AND f.bundle = :type;"
    ,array(':type'=>'voiture'));
 
    //on supprime tous les fichier de tmp-import
    rrmdir( __DIR__ . '/tmp-import' );
    if(!is_dir(__DIR__ . '/tmp-import')){
        mkdir(__DIR__ . '/tmp-import');
    }

    require __DIR__ . '/autoload.php';
    
    if(!variable_get('planetvo_server') || !variable_get('planetvo_login') || !variable_get('planetvo_pwd') || !variable_get('planetvo_code'))
        return false;
    
    $ftpAccess = new \Import\FtpAccess\FtpAccess(variable_get('planetvo_server'), variable_get('planetvo_login'), variable_get('planetvo_pwd'));
    $connect = $ftpAccess->connect();

    $codes = variable_get('planetvo_code');
    
    $aCodes = explode(',',$codes);
    
    //debug
    //$aCodes = array('ka31c1');
    
    foreach( $aCodes as $code ){
          $test = 0;
          $time_deb = time();
          $codeVO = trim($code);

          if(empty($codeVO)) continue;
          error_log('import planetVO code : '.$codeVO);
          $importer = new Import\Importer();
          $importer->setTransport($ftpAccess, $codeVO);
          $importer->importElements();

          $elements_saved = $importer->saveElements();
          watchdog('cron_planetvo', 'cron_planetvo Elements sauvegarder : '.$elements_saved);
          $time_fin = time();

        
        
    }
    //$memory = round(memory_get_usage(true)/1048576,2);
    //var_dump($memory);
    
    watchdog('cron_planetvo', 'cron_planetvo ran');
    error_log('import planetVO end');
    die();
}


/* 
 * hooks implémentés 
 * 
 * - hook_voiture_alter(&$node_voiture) //pour modifier le content type de base pour une voiture.
 * - hook_photo_voiture_alter(&$node_photo_voiture) //pour modifier un content type photo de voiture.
 * - hook_equipement_voiture_alter(&$node_equipements_et_options) //pour modifier un content type equipement et option
 * - hook_voiture_after_save_alter(&$node_voiture) //pour modifier le content type de base pour une voiture APRES la sauvegarde (on a un ID voiture)
 */


function rrmdir($dir) { 
   if (is_dir($dir)) { 
     $objects = scandir($dir); 
     foreach ($objects as $object) { 
       if ($object != "." && $object != "..") { 
         if (filetype($dir."/".$object) == "dir") rrmdir($dir."/".$object); else unlink($dir."/".$object); 
       } 
     } 
     reset($objects); 
     rmdir($dir); 
   } 
 }